// Auto-generated by scripts/gen-env-setup.mjs — DO NOT EDIT
// Preload environment-based preferences for tests
(() => {
  try {
    // provider
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.provider", "google", true);
    // stream
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.stream", true, true);
    // temperature
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.temperature", "0.7", true);
    // topP
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.topP", "1.0", true);
    // maxTokens
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.maxTokens",
      "4096# Usage:",
      true,
    );
    // requestTimeout
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.requestTimeout",
      "15000",
      true,
    );
    // openaiApiUrl
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.openaiApiUrl",
      "https://api.openai.com/v1/responses",
      true,
    );
    // openaiApiKey
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.openaiApiKey", "", true);
    // openaiApiModel
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.openaiApiModel",
      "gpt-5",
      true,
    );
    // geminiApiUrl
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.geminiApiUrl",
      "https://generativelanguage.googleapis.com",
      true,
    );
    // geminiApiKey
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.geminiApiKey", "", true);
    // geminiModel
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.geminiModel",
      "gemini-2.5-pro",
      true,
    );
    // anthropicApiUrl
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.anthropicApiUrl",
      "https://api.anthropic.com",
      true,
    );
    // anthropicApiKey
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.anthropicApiKey",
      "",
      true,
    );
    // anthropicModel
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.anthropicModel",
      "claude-sonnet-4-5-20250929",
      true,
    );
    // openaiCompatApiUrl
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.openaiCompatApiUrl",
      "https://api.openai.com/v1/chat/completions",
      true,
    );
    // openaiCompatApiKey
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.openaiCompatApiKey",
      "",
      true,
    );
    // openaiCompatModel
    Zotero?.Prefs?.set?.(
      "extensions.zotero.aiButler.openaiCompatModel",
      "gpt-3.5-turbo",
      true,
    );
  } catch (e) {
    /* ignore in non-test env */
  }
})();
export {};
