// Auto-generated by scripts/gen-env-setup.mjs — DO NOT EDIT
// Preload environment-based preferences for tests
(() => {
  try {
    // provider
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.provider", "google", true);
    // stream
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.stream", true, true);
    // temperature
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.temperature", "0.7", true);
    // topP
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.topP", "1.0", true);
    // maxTokens
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.maxTokens", "4096# Usage:", true);
    // requestTimeout
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.requestTimeout", "15000", true);
    // openaiApiUrl
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.openaiApiUrl", "REDACTED/v1/responses", true);
    // openaiApiKey
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.openaiApiKey", "REDACTED", true);
    // openaiApiModel
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.openaiApiModel", "gpt-5", true);
    // geminiApiUrl
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.geminiApiUrl", "REDACTED", true);
    // geminiApiKey
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.geminiApiKey", "REDACTED", true);
    // geminiModel
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.geminiModel", "gemini-2.5-pro", true);
    // anthropicApiUrl
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.anthropicApiUrl", "REDACTED", true);
    // anthropicApiKey
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.anthropicApiKey", "REDACTED", true);
    // anthropicModel
    Zotero?.Prefs?.set?.("extensions.zotero.aiButler.anthropicModel", "claude-sonnet-4-5-20250929", true);
  } catch (e) { /* ignore in non-test env */ }
})();
export {};
