// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "openaiApiKey": string;
      "openaiApiUrl": string;
      "openaiApiModel": string;
      "openaiCompatApiKey": string;
      "openaiCompatApiUrl": string;
      "openaiCompatModel": string;
      "geminiApiUrl": string;
      "geminiApiKey": string;
      "geminiModel": string;
      "anthropicApiUrl": string;
      "anthropicApiKey": string;
      "anthropicModel": string;
      "openRouterApiUrl": string;
      "openRouterApiKey": string;
      "openRouterModel": string;
      "volcanoArkApiUrl": string;
      "volcanoArkApiKey": string;
      "volcanoArkModel": string;
      "temperature": string;
      "enableTemperature": boolean;
      "maxTokens": string;
      "enableMaxTokens": boolean;
      "topP": string;
      "enableTopP": boolean;
      "stream": boolean;
      "requestTimeout": string;
      "mineruApiKey": string;
      "summaryPrompt": string;
      "customPrompts": string;
      "summaryMode": string;
      "multiRoundPrompts": string;
      "multiRoundFinalPrompt": string;
      "multiSummarySaveIntermediate": boolean;
      "maxRetries": string;
      "batchSize": string;
      "batchInterval": string;
      "autoScan": boolean;
      "scanInterval": string;
      "pdfProcessMode": string;
      "imageSummaryAspectRatio": string;
      "imageSummaryResolution": string;
      "theme": string;
      "fontSize": string;
      "autoScroll": boolean;
      "windowWidth": string;
      "windowHeight": string;
      "saveChatHistory": boolean;
      "sidebarNoteCollapsed": boolean;
      "sidebarImageCollapsed": boolean;
      "notePrefix": string;
      "noteStrategy": string;
      "mindmapPrompt": string;
      "mindmapExportPath": string;
    };
  }
}
